[Feature] 리더보드 기수별 랭킹 추가
42Statistics/42Stat-Frontend pull request #300
Opened 2023-09-30 07:17 UTC by yoopark

## Summary

<img width="728" alt="image" src="https://github.com/42Statistics/42Stat-Frontend/assets/61629480/f0c2524d-d997-4621-8e21-eccf0e59a7ea">

## Describe your changes

- Select 제작
- 기존 Select -> FormSelect로 rename
- Leaderboard 기수 Select 추가
- Leaderboard 기능 분리를 중심으로 한 리팩토링 진행
- 기존 searchParams 변경을 navigate로 처리하였었음 -> setSearchParams로 변경
- coalition_score -> score rename

### 로직 간단 설명
> 페이지별 로직이 반복되는 부분이 많아 ExpIncrement 하나만 보셔도 무방합니다. 

1. LeaderboardLayout 단에서 Promo fetch, context에 저장
https://github.com/42Statistics/42Stat-Frontend/blob/595b73050283bc30a24cbddc696cd4ccd7de55cd/app/src/Leaderboard/index.tsx#L45-L47

2. 각 페이지에서 SearchParam parse
https://github.com/42Statistics/42Stat-Frontend/blob/595b73050283bc30a24cbddc696cd4ccd7de55cd/app/src/Leaderboard/pages/ExpIncrement/index.tsx#L1-L15

3. Content에서 핵심 로직 처리
[LeaderboardExpIncrementContent.tsx 바로가기](https://github.com/42Statistics/42Stat-Frontend/blob/595b73050283bc30a24cbddc696cd4ccd7de55cd/app/src/Leaderboard/pages/ExpIncrement/components/LeaderboardExpIncrementContent.tsx
)

## Issue number and link
- close #299

2023-09-30 07:33 UTC, yoopark commented
<img width="474" alt="image" src="https://github.com/42Statistics/42Stat-Frontend/assets/61629480/38ff73e4-1933-4f5d-aefa-f3b104f89a00">

반응형 고려를 깜박해서 추가하였습니다 😅

2023-09-30 16:28 UTC, jpham005 requested changes
풀리퀘 읽고 든 생각은, 일단 제가 생각하는 그림이랑 굉장히 다르다는 거였는데요,
yopark 님의 의도가 있을테니, 그냥 읽어보시고 답변 해주시고, 어쩌면 오프라인에서 회의를 해보는게 나을 수도 있어보여요.

일단 Context, Provider  가 너무 남용되었다고 생각했고,
searchParams 구조도 좀 바꾸면 좋겠다고 생각했어요. re-render 가 안일어나는 것도 아니고, LeaderboardContent 부분의 로직 분리가 제대로 되어 있는 것 같다는 느낌도 없었습니다.

1. Context, Provider 를 엄청 많이 만드셨는데, jotai 의 기능을 사용하지 않은 이유.
Select 의 경우 Provider 여러개가 한번에 적용이 되어있는데, 이런 경우 특히 차이가 두드러집니다.
2. searchParam 을 페이지마다 따로 처리한 이유.
DateTemplate 의 차이때문에 그런 작업이 있던 것 같지만, 사실 그냥 무조건 Date 포함해서 처리하면 밑에서 필요한 것만 가져다 쓰면 됩니다.
3. Select 의 비직관성.
Content 와 Layout 이 하나의 묶음이 되어야 한다고 생각하는데, 그렇게 하지 않은 이유가 궁금합니다.

2023-09-30 16:28 UTC, jpham005 commented on app/src/Leaderboard/pages/Comment/utils/parseLeaderboardCommentSearchParams.ts
이 parse 함수들이 페이지마다 따로 있어야할까요?

2023-09-30 16:28 UTC, jpham005 commented on app/src/Leaderboard/pages/Comment/components/LeaderboardCommentContent.tsx
> +            }
이건 어떻게든 분리를 하는게 좋을 것 같아요.
예를 들어 코알리숑으로 분류하는 기능 하나만 추가되더라도 상당히 보기 힘들 것 같습니다.

2023-09-30 16:35 UTC, jpham005 commented on app/src/Leaderboard/pages/Comment/components/LeaderboardCommentContent.tsx
> +                defaultRenderValue={promo !== null ? `${promo}기` : undefined}
이런 것들도 parseInt 가 아닌 String 을 사용한 이유가 궁금했고,
`${promo}기` 도 가능한 사용법일 수 있겠지만 함수 따로 만들어도 좋을 것 같구요.

2023-10-01 03:22 UTC, yoopark commented on app/src/Leaderboard/components/LeaderboardPromoListFetcher.tsx
> +
PromoList 부르는 과정에서 에러가 발생하면, Select에 기수는 없고 전체 보기만 있을텐데 그 상태로 진행해도 괜찮다고 생각했습니다. 

약간 안일했나요?

2023-10-01 03:24 UTC, yoopark commented on app/src/Leaderboard/components/LeaderboardPromoListFetcher.tsx
> +    </LeaderboardPromoListContext.Provider>
https://github.com/42Statistics/42Stat-Frontend/blob/1ecad3faf7b1e318ec33d2194327be2c2d1adf0d/app/src/Leaderboard/contexts/LeaderboardPromoListContext.tsx#L5-L8

이 부분 말씀하시는 건가요?

2023-10-01 03:38 UTC, yoopark commented on app/src/Leaderboard/pages/Comment/utils/parseLeaderboardCommentSearchParams.ts
통합하였습니다. 

https://github.com/42Statistics/42Stat-Frontend/pull/300/commits/4d5f85584017a7052fc8f0eab7f5a18ebfa7c0f5

2023-10-01 03:38 UTC, yoopark commented on app/src/@shared/ui-kit/Select/Select.tsx
> +  const [value, setValue] = useState<string | null>(defaultValue ?? null);
처리하였습니다. 
https://github.com/42Statistics/42Stat-Frontend/pull/300/commits/2a064e30bec4df27228a3d12ed59c4a162f75531

2023-10-01 03:39 UTC, yoopark commented on app/src/@shared/ui-kit/Select/SelectItem.tsx
> +    value: currentValue,
처리하였습니다. 
https://github.com/42Statistics/42Stat-Frontend/pull/300/commits/2a064e30bec4df27228a3d12ed59c4a162f75531

2023-10-01 03:39 UTC, yoopark commented on app/src/@shared/ui-kit/Select/SelectItem.tsx
> +  const active = value === currentValue;
처리하였습니다. 
https://github.com/42Statistics/42Stat-Frontend/pull/300/commits/2a064e30bec4df27228a3d12ed59c4a162f75531

2023-10-01 03:40 UTC, yoopark commented
나머지는 밤에 다녀와서 진행하겠습니당 🙇 열심히 리뷰해주셔서 언제나 감사할 따름입니다

2023-10-01 05:05 UTC, jpham005 commented on app/src/Leaderboard/components/LeaderboardPromoListFetcher.tsx
> +    </LeaderboardPromoListContext.Provider>
네 맞습니다

2023-10-01 05:14 UTC, yoopark commented on app/src/Leaderboard/components/LeaderboardPromoListFetcher.tsx
> +    </LeaderboardPromoListContext.Provider>
Promo[] | undefined | null 이지, (Promo | null)[] 타입이 아닌데요? 
궁금하신 점을 제가 제대로 이해하지 못한 것 같아요. 
Provider에서 값이 채워지고, useGet~ 훅을 사용하면 타입이 좁혀지는 방식입니다.

| undefined 타입을 추가한 이유는 백엔드 스키마 상 타입이 그렇게 정의가 되어 있어서 불가피하게 추가했습니다.

2023-10-01 05:31 UTC, jpham005 commented on app/src/Leaderboard/components/LeaderboardPromoListFetcher.tsx
> +
useQuery 자체는 error 가 발생했을때 data 에 뭐가 있을지 보장해주지 않는 것으로 아는데요, 의도한 부분이니 다행이지만 명시적으로 처리하는게 저는 더 마음에 드네요.
코드 바뀔 때 신경 덜 써도 될거구요.

2023-10-03 14:29 UTC, yoopark commented on app/src/Leaderboard/pages/Comment/index.tsx
>      </>
넵, 지금 상태에서는 성욱님 말씀이 맞는 것 같아요. 

아래 커밋에 반영하였습니다.
https://github.com/42Statistics/42Stat-Frontend/pull/300/commits/534a17525e37be116b30c460e45db769e81f33ef

2023-10-03 15:21 UTC, yoopark commented on app/src/Leaderboard/components/Leaderboard/LeaderboardHeader.tsx
> +    </Layout>
오래 고민하지 않고 만들다보니 저런 식의 구조가 탄생했던 것 같습니다. 
left, right에 다른 요소가 들어오는 것도 아닌데 저런 식으로 나누는 건 불필요하다고 동감합니다. 

해당 커밋에서 `LeaderboardHeader`의 구조를 변경하였습니다. 
https://github.com/42Statistics/42Stat-Frontend/pull/300/commits/e4345e360d50c54b2bf7563d88923ccea6ed7814

2023-10-03 15:22 UTC, yoopark commented on app/src/Leaderboard/pages/Comment/components/LeaderboardCommentContent.tsx
> +            }
해당 커밋에서 Select를 LeaderboardHeader 내부로 집어넣었습니다. 
https://github.com/42Statistics/42Stat-Frontend/pull/300/commits/e4345e360d50c54b2bf7563d88923ccea6ed7814

2023-10-03 15:42 UTC, yoopark commented
> Select 의 비직관성.
> Content 와 Layout 이 하나의 묶음이 되어야 한다고 생각하는데, 그렇게 하지 않은 이유가 궁금합니다.

나름 UI Kit라서 Compound Component 패턴으로 짜보려고 했는데, 
**사용법을 이미 알고 있는 사람이 아니면 사용할 수 없다**는 단점을 언급해주셔서 새로웠습니다. 미처 생각하지 못하던 내용이었습니다. 감사합니다. 

우선, 아래의 레퍼런스를 참고하여 Select 컴포넌트를 제작하였습니다. 
[Select - hadcn/ui](https://ui.shadcn.com/docs/components/select)

말씀해주신 단점을 받아들여 Select 컴포넌트 내에 trigger와 values를 전달하는 방식으로 짜보려고 하였으나 한 가지 문제가 있습니다. 

<img width="237" alt="image" src="https://github.com/42Statistics/42Stat-Frontend/assets/61629480/279934f9-3f58-409a-aca0-75729939bd5e">

SelectItem의 UI가 단순히 value를 띄우는 것이라면 compound componen pattern을 사용하지 않고 만들 수 있습니다. 
하지만, 저희는 `1`, `기`, `시작일`과 같이 SelectItem의 UI를 자유롭게 제작하고 싶은 상황이기 때문에 단순히 values를 전달하는 방식으로는 해당 컴포넌트를 제작할 수 없습니다. 

따라서 Select의 리팩토링 문제와는 별개로, compound component pattern을 사용하는 것은 유지하는 것이 낫지 않을까 생각합니다.

Storybook을 통해 사용법을 설명하는 방식으로 보완하면 어떨까 제안드립니다.

2023-10-03 15:45 UTC, yoopark commented on app/src/@shared/ui-kit/Select/Select.tsx
> +      </SelectValueContext.Provider>
해당 의문에 대한 답변을 아래 코멘트로 남겼습니다.

2023-10-03 22:03 UTC, jpham005 commented on app/src/Leaderboard/components/LeaderboardPromoListFetcher.tsx
> +    </LeaderboardPromoListContext.Provider>
일단 백엔드 스키마는
```graphql
type LeaderboardMetadata {
  promoList: [Promo!]!
}
```
위와 같이 Non-nullable 입니다.
아마 data 의 status 검사가 제대로 이루어지지 않아서 undefined 타입이 섞여있지 않았을까 싶네요.

(useContext 를 통한 provider 구현을 직접 해야하는지 차치하고)
Provider 는 결국 어떤 복잡한 과정의 set 을 대신 처리하고, 간단한 get 만 노출시키는 방식이라 봅니다.
그렇다면 set 을 처리하는 과정에서 nullable 한 값을 검사하여 이를 error 처리 하고,
정상적인 상태만을 provider 의 내부 변수로 갖고 있는 것이 바람직하다는 의견입니다.
굳이 비정상적인 상태를 포함시킬 이유도 없을 뿐더러, 그걸 사용하기 전까지 error 발생을 미룰 이유도 현재 없구요.

아래와 같은 모양의 코드를 기대해볼 수 있습니다.
```tsx
// 그나저나 이게 이름이 Provider 가 되는게 맞지 않을까요?
// Fetcher 는 Provider 역할을 한다고 기대하기 어려운 이름 같아요.
const LeaderboardPromoListFetcher = () => {
  const { data, loading, error } = useQuery(GET_PROMO_LIST);

  if (loading) {
    return null;
  }
  
  if (isApiError(data, error)) {
    // handle error;
  }
  
  return (
    <...Provider value={promoList}> // context 에 전달되는 value 는 nullable 하지 않은 유효한 값
      {chlidren}
    </...>
  )
}

// 혹은 assertion
const isApiError = ({ data, error }: ReturnType<useQuery...>): data is Promo[] => {
  if (!error) {
    return true;
  }
  
  return  (data?.promoList ?? null) === null
}
```

2023-10-07 04:54 UTC, yoopark commented on app/src/Leaderboard/pages/Comment/components/LeaderboardCommentContent.tsx
> +                defaultRenderValue={promo !== null ? `${promo}기` : undefined}
`${promo}기`는 처리하였습니다. 
https://github.com/42Statistics/42Stat-Frontend/pull/300

제가 제작한 Select 컴포넌트에 string을 value로 받을 수 있도록 처리했기 때문에 `String(promo)`를 하여 넘깁니다. 혹시 더 좋은 방법이 있을까요?

2023-10-07 08:50 UTC, yoopark commented on app/src/@shared/ui-kit/Select/Select.tsx
> +      >
컴파운드 컴포넌트 패턴에서 자식 컴포넌트로 상태를 넘겨주기 위하여 불가피하게 사용되었음을 직접 만나 알려드렸습니다.

2023-10-07 08:51 UTC, yoopark commented on app/src/Leaderboard/components/LeaderboardPromoListFetcher.tsx
> +    </LeaderboardPromoListContext.Provider>
처리하였습니다. 
https://github.com/42Statistics/42Stat-Frontend/pull/300/commits/859e9070461ea8286240572af77ed28e0250e928

2023-10-07 08:51 UTC, yoopark commented on app/src/Leaderboard/components/LeaderboardPromoListFetcher.tsx
> +
처리하였습니다. 
https://github.com/42Statistics/42Stat-Frontend/pull/300/commits/859e9070461ea8286240572af77ed28e0250e928

2023-10-07 08:54 UTC, yoopark commented on app/src/@shared/ui-kit/Select/Select.tsx
> +      </SelectValueContext.Provider>
Chakra UI, Radix UI를 사용하는 예시를 보여드리면서 설명드렸습니다. 
기존 컴파운드 컴포넌트 로직을 Leaderboard Select에서 드러내 사용하는 쪽으로 일단 결정하였습니다. 

이후 리팩토링 과정에서,

```
<LeaderboardSelect
  trigger={<Component />}
  contents={
    [ .... ]
  } 
/>
```

의 느낌으로 코드를 수정할 여지도 있음을 알립니다.

2023-10-07 09:06 UTC, yoopark commented
Select 컴포넌트 내에서의 React Context 사용을 Jotai로 대체하고자 하였으나, 찾지 못하여 해당 PR은 머지하고 후속 이슈로 남깁니다. 

- #302

2023-10-07 09:17 UTC, jpham005 commented on app/src/Leaderboard/pages/Comment/components/LeaderboardCommentContent.tsx
> +                defaultRenderValue={promo !== null ? `${promo}기` : undefined}
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/String (Return Value 부분 보세요)
String constructor 를 쓰기보단 toString 이나 template literal 쓰는게 어떨까 싶습니다.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toString

parseInt 의 경우 제가 변환 방향을 거꾸로 생각해서 생긴 오류입니다.

2023-10-07 09:19 UTC, jpham005 approved these changes

2023-10-07 09:20 UTC, yoopark commented on app/src/Leaderboard/pages/Comment/components/LeaderboardCommentContent.tsx
> +                defaultRenderValue={promo !== null ? `${promo}기` : undefined}
수정하고 머지하겠습니다.

2023-10-07 11:40 UTC, merged