[Feat] 기본 Dialog Modal 추가 및 로그아웃 에러 핸들링
42Statistics/42Stat-Frontend pull request #353
Opened 2023-10-24 09:07 UTC by 42sungwook

## Summary
로그아웃 에러 핸들링, 로그아웃시 새로고침

## Describe your changes
- Dialog 모달 추가 (간편하게 title, description, confirmText를 인자로 받아서 쓸 수 있는 기본 모달)
- 로그아웃 시도시 error면 모달이 뜨도록 수정
- 로그아웃시 route로 이동이 아닌 새로고침으로 수정 (atom 상태가 남아있어 다른 계정으로 로그인시 상태가 남아있는 문제)

## Issue number and link

2023-10-24 10:31 UTC, yoopark requested changes

2023-10-24 10:37 UTC, 42sungwook commented on app/src/@core/components/Modal/Dialog.tsx
> +};
AlertDialog에 atom을 설정해서 provider에 바로 사용할 수 있나요?
기본 Dialog를 쓰고 싶어서 AlertDialog를 가져와봤는데 open, close를 어떻게 해야될지 모르겠더라고요

2023-10-24 10:38 UTC, 42sungwook commented on app/src/Setting/sections/AccountSection/LogoutButton.tsx
> +    window.location.reload(); // atom 초기화를 위해 새로고침
제걸로 로그인했다가 테스트 계정 (Visitor 계정)으로 로그인하면 Navbar에 제 사진이 뜨더라고요

2023-10-24 10:41 UTC, yoopark commented on app/src/@core/components/Modal/Dialog.tsx
> +};
Ref. https://github.com/42Statistics/42Stat-Frontend/blob/99c710e6b289aac7926c67e06bbc3de53fd7bb8f/app/src/FtOAuthRedirect/index.tsx#L30

이런 식으로 AlertDialog를 사용할 수 있습니다. useDisclousre를 atom으로 빼시면 전역으로 사용하실 수 있어요! 이번에 useNavigate 고치면서 모달 쪽 손 좀 봐야겠군요..ㅎㅎ

2023-10-24 10:56 UTC, 42sungwook commented on app/src/@core/components/Modal/Dialog.tsx
> +};
보여주신 예시는 AlertDialog 자체를 return하는데 제가 하고 싶은거는 provider에서 관리를 해주는거라서요.
ModalProvider에 AlertDialog로 기본 Dialog를 추가해도 비슷하게 보일 것 같긴한데
상관없을까요?

2023-10-25 05:47 UTC, yoopark commented on app/src/@core/components/Modal/Dialog.tsx
> +};
> ModalProvider에 AlertDialog로 기본 Dialog를 추가해도 비슷하게 보일 것 같긴한데
상관없을까요?

정확히 어떤 걸 만들고 싶은지 이해를 못했습니다..! 
AlertDialog를 이용해서 특정 다이얼로그를 만들고, 그 다이얼로그를 ModalProvider에 넣는 방식으로 제작하시면 될 것 같습니다.

2023-10-25 05:48 UTC, yoopark commented on app/src/Setting/sections/AccountSection/LogoutButton.tsx
> +    window.location.reload(); // atom 초기화를 위해 새로고침
아하 그렇구만요. 알겠습니당. 
나중에 `/logout`으로 navigate 한 다음에 그 페이지에서 처리하는게 깔끔할 듯하군요.

2023-10-25 05:54 UTC, 42sungwook commented on app/src/@core/components/Modal/Dialog.tsx
> +};
지금 있는 calculator, reloginDialog와는 다르게 특정 로직(확인을 눌렀을 때 focus 제어, 저장소 클리어)이 없이 정보만 알리고 확인을 눌렀을 때는 닫히는 모달을 만드려고 했습니다

2023-10-25 05:55 UTC, 42sungwook commented on app/src/@core/components/Modal/Dialog.tsx
> +};
뭔가 의미 전달이 잘 안된 것 같네요.. Dialog가 아닌 InfoDialog로 명칭을 바꾸면 이해가 될까요..?

2023-10-25 05:57 UTC, 42sungwook commented on app/src/Setting/sections/AccountSection/LogoutButton.tsx
> +    window.location.reload(); // atom 초기화를 위해 새로고침
페이지를 따로 만드는게 어떻게 더 좋은지 잘 모르겠습니다! 결국 atom의 상태를 초기화하려면 새로고침이 가장 효과적인 것 아닌가요?

2023-10-25 06:44 UTC, yoopark commented on app/src/@core/components/Modal/Dialog.tsx
> +};
그게 AlertDialog 아닌가요? AlertDialog를 이용하여 LogoutFailedDialog 같은 걸 만드신 다음에 ModalProvider에 넣는 방식으로도 제작할 수 있을 것 같습니다.

2023-10-25 06:45 UTC, yoopark commented on app/src/Setting/sections/AccountSection/LogoutButton.tsx
> +    window.location.reload(); // atom 초기화를 위해 새로고침
그냥 다른 얘기입니다! 페이지로 뺀 다음, 거기서 새로고침해도 되긴 합니다. 저는 SPA의 특징을 살려서 최대한 새로고침은 피하고 싶어서요. 거기서 사용하고 있는 atom을 리셋하는 방식을 생각해보거나.. 빼면서 생각해보면 될 것 같습니다.

2023-10-25 12:28 UTC, yoopark commented on app/src/@core/atoms/reLoginDialogAtom.ts
> +export const reLoginDialogAtom = atom(false);
위 코멘트와 동일

2023-10-25 12:35 UTC, 42sungwook commented on app/src/@core/atoms/reLoginDialogAtom.ts
> +export const reLoginDialogAtom = atom(false);
둘 다 수정했습니다

2023-10-25 12:38 UTC, yoopark approved these changes
예전에 만든 로그아웃 로직의 빈틈을 발견하시고 고쳐주셔서 정말 감사합니다 🙇‍♂️

2023-10-25 12:59 UTC, merged