feat: :sparkles: routes basic layout
42Statistics/42Stat-Frontend pull request #4
Opened 2023-03-08 12:33 UTC by yoopark

PR 연습 삼아 올려봅니다 ㅎㅎ

이런 식으로 Routing 하려 합니다. 
파일이나 layout이 그리 다양하지 않아서 App.tsx에 일단 몰아서 작성했습니다. (이후 lazyImport 등 생각하면 수정될 수도 있어요)
jaham님 원래 레포 보다가 Outlet이라는 좋은 기능을 알게 되었네요 👍

2023-03-08 12:51 UTC, jpham005 commented on app/src/layouts/DashboardLayout.tsx
> +export const DashboardLayout = () => {
```ts
메인 컴포넌트는 export const로
```
이런거 컨벤션 문서를 discussion repo에 하나 만들거나 하는게 나을지도?
제가 하나 만들어두던가 할게요.
생각날때마다 하나씩 적읍시다.

2023-03-08 12:58 UTC, yoopark commented on app/src/stores/useAuthStore.ts
> +type useAuthStoreProps = {
이건 항상 헷갈렸던 부분인데, useAuthStore 에서 꺼내오는 모습이 뭔가 useState에서 꺼내오는 느낌이어서 쓰는 것 같습니다. 
사실 [zustand 공식문서](https://github.com/pmndrs/zustand)에서 use를 붙이길래 습관적으로 붙이는데, 확실히 떼는게 직관적으로 읽히긴 하네요. 

Props는 사실 지을 변수명 없을 때 습관적으로 붙이는 이름입니다. 혹시 저런 경우에 자함님은 네이밍 어떻게 하시나요?

2023-03-08 12:59 UTC, yoopark commented on app/src/layouts/DashboardLayout.tsx
> +export const DashboardLayout = () => {
원래가 다 export const 아닌가요? 저는 항상 저렇게 써가지고...

2023-03-08 13:01 UTC, jpham005 commented on app/src/layouts/DashboardLayout.tsx
> +export const DashboardLayout = () => {
```ts
1. export function Dashboard
2. function Dashboard
... export DashBoard
3. export default DashBoard
```
위의 예시에서 보이듯, function 키워드의 사용 여부와 default 키워드의 사용 여부는 차이가 있긴 하죠.

2023-03-08 13:01 UTC, yoopark commented on app/src/App.tsx
> +        />
/home 으로 접근했을 때 체크 안하긴 하네요..ㅎㅎ 근데 위에서 말한 해결책 조금 더 자세히 설명해주실 수 있나요? 정확히 어떻게 해소할지 느낌이 안와서요. isAuthenticated는 어디서 체크해야 하는거죠?

2023-03-08 13:05 UTC, jpham005 commented on app/src/stores/useAuthStore.ts
> +type useAuthStoreProps = {
<img width="688" alt="Screen Shot 2023-03-08 at 10 02 30 PM" src="https://user-images.githubusercontent.com/76723089/223720009-c5aed8c1-f893-4110-a096-6bd44e12a55f.png">
그래서 저도 문서를 슥 보고 왔는데,
useSomethingStore 형태는 좋다고 생각합니다.

하지만 generic으로 들어가는 것들은 결국 '무엇의 Store인가?' 라는게 중요한 포인트 같아요.

때문에 useAuthStore같은 경우,
```ts
type Auth = {
  ...
}

const useAuthStore = create<Auth>(...)
```
형태가 좋다고 생각합니다.

2023-03-08 13:12 UTC, jpham005 commented on app/src/App.tsx
> +        />
사실 path가 필요없었네요.
```tsx
<Login />
<Route element={AuthCheck}> // 로그인이 안되어있으면 Login으로 navigate하는 로직
  <Home/>
</Route>
```

2023-03-08 13:12 UTC, yoopark commented on app/src/stores/useAuthStore.ts
> +type useAuthStoreProps = {
오호 더 직관적이네요! 수정하도록 하겠습니다

2023-03-08 13:13 UTC, jpham005 commented on app/src/App.tsx
> +        />
React Router Dom이 nested 문법을 지원해서,
뭔가를 특정 Router(들)에 적용하고 싶은 경우에 활용하면 편합니다.
https://reactrouter.com/en/main/route/route#layout-routes

2023-03-08 13:14 UTC, jpham005 commented on app/src/layouts/DashboardLayout.tsx
> +export const DashboardLayout = () => {
사실 정해놓고 그거에 맞춰서 쓰는게 중요한 부분같긴 합니다.
discussion으로 파두려고 했는데 생각보다 부적절한 느낌이네요....
Wiki나 md 파일 하나 만드는게 나을 것 같기도 해요. 다같이 작성하려면

2023-03-08 13:15 UTC, jpham005 commented on app/src/stores/useAuthStore.ts
> +type useAuthStoreProps = {
덧붙이자면, React에 Props라는 개념이 이미 있어서 유의하긴 해야할 것 같아요.

2023-03-08 13:44 UTC, yoopark commented on app/src/App.tsx
> +        />
아 만들어보고 있는데 뭔가 애매한 것 같습니다. 지금 제가 만들려고 하는게 `/` -> LoginPage, `/home` -> HomePage 인데, 사실 바로 **리다이렉션**하는 로직은 `/`로 접근할 때 한번밖에 안 등장해서 굳이 AuthCheck로 뺄 필요가 없을 것 같습니다. 

대신 말씀해주신 방식을 기존 DashboardLayout을 적용하는 모든 Route에 AuthGuard (로그인이 필요합니다 **알림을 띄우는** 로직)를 적용시키면 어떨까 싶습니다. 그렇게 하면 /home으로 바로 접근해도 `/`으로 튕겨나올 것 같습니다.

2023-03-08 13:51 UTC, jpham005 commented on app/src/App.tsx
> +        />
괜찮네요.
AuthCheck같은 걸 만드려고 했던 이유는, 추후에 인증 여부를 검증하는 로직이 더 복잡해질 가능성도 염두해둔 부분이긴 합니다.

ex. 로그인은 했는데 intra 인증이 안됐다던가...

사실 어차피 이부분은 로그인 로직이 확정되어야 하는 부분도 있고, 추후 수정이 어려울 것 같지도 않아서 지금은 이정도로 정리해도 좋을 것 같습니다.

AuthGuard만 만들어서 푸쉬 부탁드려요!

2023-03-08 14:52 UTC, jpham005 requested changes

2023-03-08 14:52 UTC, jpham005 commented on app/src/guards/AuthGuard.tsx
> +  }, []);
훅(useEffect)에서 사용하는 dependency array에 훅 안쪽의 모든 외부 변수들이 들어가야 하지 않을까요?

클로저 개념때문에, 항상 state를 적절히 반영하려면 그렇게 해야 하는 것으로 알고있습니다.

2023-03-09 14:43 UTC, jpham005 commented on app/.eslintrc.json
> +    "es2021": true
tsconfig에는 target이 esnext였던 것 같은데,
이 부분 괜찮나요?

2023-03-09 14:48 UTC, yoopark commented on app/.eslintrc.json
> +    "es2021": true
esnext가 가장 최신인가요? 그냥 eslint --init 해서 나온 react-ts 설정 쓴거라 크게 신경 안썼는데 수정하겠습니당

2023-03-09 14:52 UTC, jpham005 approved these changes
첫 풀리퀘인데 고생 많으셨습니다.
아무래도 초기에 맞춰야 하는 부분들이 많다보니 신경써야할게 더 많은 느낌이네요 ㅎㅎ

2023-03-09 15:01 UTC, yoopark commented
초장에 정확히 잡는게 중요하죠 ㅎㅎ 많이 배워갑니다

2023-03-09 15:01 UTC, merged