[HotFix] dailyActivity 다른 사람 활동이 보이는 버그
42Statistics/42Stat-Frontend pull request #431
Opened 2023-12-22 14:42 UTC by 42sungwook

## Summary
selectedDailyActivityAtom을 초기화하지 않아서 생긴 버그

<img width="663" alt="스크린샷 2023-12-22 오후 11 41 22" src="https://github.com/42Statistics/42Stat-Frontend/assets/106149304/6dd37adc-d1a3-4ba3-a4b5-29846c7c5bc9">

## Describe your changes
atom을 초기화할 필요는 없는 것 같고 atom에 login을 추가해서 useContext의 login이랑 일치하지 않으면 카드를 로딩으로 뜨게 바꿨습니다!

## Issue number and link

2023-12-22 14:43 UTC, 42sungwook commented
메인에다가도 올리려했는데 저번 배포 이후 핫픽스할 때 dev 브랜치를 배포하신 건가요?
main에는 이전 핫픽스가 적용되지 않은 것 같아서 헷갈리네요

2023-12-23 04:19 UTC, yoopark requested changes
같은 컴포넌트여서 새로운 데이터를 불러오기 전까지는 이전 유저의 데이터가 뜨는 경우가 발생한다는 말이군요! 제가 이해한 게 맞다면 React 공식문서에 해당 문제에 대한 더 깔끔한 해결 방법이 있습니다. 

Ref. https://ko.react.dev/learn/preserving-and-resetting-state#clear-an-image-while-its-loading

2023-12-23 04:20 UTC, yoopark commented
> 메인에다가도 올리려했는데 저번 배포 이후 핫픽스할 때 dev 브랜치를 배포하신 건가요? main에는 이전 핫픽스가 적용되지 않은 것 같아서 헷갈리네요

- #426 
- #427 

이거 말씀하시는 건가요? 어떤 문제가 있는지 말씀해주세요.

2023-12-23 04:45 UTC, 42sungwook commented
메인 브랜치에 커밋 하나가 덜 올라가있어서요!

2023-12-23 04:48 UTC, 42sungwook commented
올려주신 참고문서가 지금 케이스에 해당하는 내용인지는 잠깐 봐서는 모르겠네요. 오늘 약속이 있어서 오늘 밤이나 내일 다시 봐볼게요

2023-12-23 04:52 UTC, 42sungwook commented
지금 잔디 카드에서 api를 불러오는데 활동상세카드는 잔디 카드의 하위 컴포넌트가 아닌게 문제였던 것 같아요

2023-12-24 06:52 UTC, yoopark commented on app/src/Profile/dashboard-contents/General/DailyActivityDetail/index.tsx
>      return <DashboardContentLoading title={title} />;
이 코드가 약간 걸리긴 하는데.. 혹시 수정할 수 있는 방법이 없을까요? 
login !== activityLogin이 발생했을 때 Loading 상태를 벗어나는 과정에 대하여 한번 설명해주시면 감사하겠습니다.

2023-12-24 06:56 UTC, 42sungwook commented on app/src/Profile/dashboard-contents/General/DailyActivityDetail/index.tsx
>      return <DashboardContentLoading title={title} />;
음.. 일단 어제 링크주신 key값 넣는걸로는 안될 것 같고 좀 더 방법을 생각해볼게요. 지금은 이게 최선이네요

2023-12-24 06:59 UTC, yoopark commented on app/src/Profile/dashboard-contents/General/DailyActivityDetail/DailyActivityTimeline/index.tsx
> +        <ApolloErrorView message={'Something Went Wrong'} />
Something Went Wrong 대신에 error.message 를 사용할 수 있습니다!

2023-12-24 06:59 UTC, yoopark commented on app/src/Profile/dashboard-contents/General/DailyActivityDetail/DailyActivityTimeline/index.tsx
> +      <VStack w="100%" h="21rem">
h=100% 같은 방식으로는 할 수 없나요? '21rem'으로 설정하신 이유가 궁금합니다!

2023-12-24 07:01 UTC, 42sungwook commented on app/src/Profile/dashboard-contents/General/DailyActivityDetail/index.tsx
>      return <DashboardContentLoading title={title} />;
지금 상세활동 카드는 잔디 카드 데이터가 불려져 오기 전까지는 로딩이어야하는데 카드가 따로 나눠져 있어서
누군가의 정보에 들어갔을 때 상세활동 카드가 잔디 카드보다 먼저 렌더링되면 이전 데이터가 남아있다는게 문제에요
그래서 지금 바꾼게 잔디 카드 데이터가 불려오기 전까지는 상세활동을 로딩으로 처리한거구요

좋은 방법이 있을까요.. 아무래도 제대로 고치려면 상세활동 카드를 잔디 카드 하위 컴포넌트로 만들어야할 것 같은데 그럼 구조가 또 어떻게 될지 잘 모르겠네요

2023-12-24 07:02 UTC, 42sungwook commented on app/src/Profile/dashboard-contents/General/DailyActivityDetail/DailyActivityTimeline/index.tsx
> +      <VStack w="100%" h="21rem">
상위 컴포넌트에서 h값을 지정하지 않고 align='start'로 해서 높이값을 퍼센트로 주었을 때 컴포넌트 전체가 잡히지 않더라구요

2023-12-24 07:03 UTC, yoopark commented on app/src/Profile/dashboard-contents/General/DailyActivityDetail/index.tsx
>      return <DashboardContentLoading title={title} />;
위 사진과 같은 버그가 생겼을 때가 login !== activityLogin인 상태에 걸리는 것 같은데, 
제가 기억하기로는 저 버그가 일시적으로 데이터 로딩할 때만 생기는 게 아니라 계속 남아있었던 것으로 기억이 납니다. 

무한 로딩 상태 같은게 생기는 건 아닌거죠? 
잘 작동하기만 하면 일단 머지하고 이후에 수정할게요.

2023-12-24 07:04 UTC, yoopark commented on app/src/Profile/dashboard-contents/General/DailyActivityDetail/index.tsx
> +        <DailyLogTime dailyLogtime={dailyLogtime} color={color} />
여기서 h='100%' 해도 안되는 건가요?

2023-12-24 07:05 UTC, yoopark commented on app/src/Profile/dashboard-contents/General/DailyActivityDetail/DailyActivityTimeline/index.tsx
> +      <VStack w="100%" h="21rem">
https://github.com/42Statistics/42Stat-Frontend/pull/431/files/2a9c292e872db8b3e753dec8519d771c0fca7446..a248f9ddf4e24ebb2f4938f2e935875b001bd053#r1435774721

2023-12-24 07:06 UTC, 42sungwook commented on app/src/Profile/dashboard-contents/General/DailyActivityDetail/index.tsx
>      return <DashboardContentLoading title={title} />;
그 부분에 대해서는 댓글 남겨주신 분한테 다시 물어봐야겠네요. 저는 아무리 테스트해도 이전 데이터가 남아있진 않았어요.

2023-12-24 07:09 UTC, 42sungwook commented on app/src/Profile/dashboard-contents/General/DailyActivityDetail/index.tsx
> +        <DailyLogTime dailyLogtime={dailyLogtime} color={color} />
여기서 100%하면 내용이 중앙정렬되는데
아마 대쉬보드카드 레이아웃에 중앙정렬되어있어서 그런 것 같네요
고쳐볼게여!

2023-12-24 07:16 UTC, yoopark commented on app/src/Profile/dashboard-contents/General/DailyActivityDetail/index.tsx
>      return <DashboardContentLoading title={title} />;
아 그렇군요. 고치기 전에는 그 버그가 발생했었는데 고치고 나서 그런 경우가 없다는 말씀이시죠? 그러면 일단은 머지해도 될 것 같습니다.

2023-12-24 07:21 UTC, 42sungwook commented
높이는 고쳤는데 로딩처리하는 부분은 좀 더 생각해볼게요.
무한로딩걸릴 때가 잔디 데이터를 불러오는데 실패했을 때 무한로딩이 걸릴 수 있는데 어떻게 고칠지는 많이 고민되네요

2023-12-24 07:22 UTC, yoopark approved these changes
연휴에 코딩하느라 고생 많으십니다 🎄🎄🎄 Merry Christmas

2023-12-24 07:23 UTC, 42sungwook commented
🎁 메리 크리스마스~~🎄🎄🎄

2023-12-24 07:25 UTC, 42sungwook commented on app/src/Profile/dashboard-contents/General/DailyActivityDetail/index.tsx
> +        <DailyLogTime dailyLogtime={dailyLogtime} color={color} />
사실 문제는 justify='center'를 안해서 생겼다는 ㅋㅋ align이 아니라 왜 justify일까요 VStack인데..🤔

2023-12-24 07:27 UTC, 42sungwook commented on app/src/Profile/dashboard-contents/General/DailyActivityDetail/index.tsx
>      return <DashboardContentLoading title={title} />;
아뇨 고치기 전에도 이전 데이터가 남아있는 경우는 없었어요. 인터넷이 느려서 몇초정도 남아있을 수 있는데 제 생각에는 그 때 캡처해서 주신게 아닐까 싶네요?

2023-12-24 07:29 UTC, yoopark commented on app/src/Profile/dashboard-contents/General/DailyActivityDetail/index.tsx
>      return <DashboardContentLoading title={title} />;
오잉? 그러면 버그가 어떻게 발생하는지 모르고 그냥 고치신건가요? 어떻게 그럼 버그가 고쳐진지를 알 수 있죠..?

2023-12-24 07:30 UTC, 42sungwook commented on app/src/Profile/dashboard-contents/General/DailyActivityDetail/index.tsx
>      return <DashboardContentLoading title={title} />;
그러니까 로딩단계에서 저렇게 이전 데이터로 보여지는걸 확인한거죠
로딩 부분을 고친거구요

2023-12-24 07:31 UTC, yoopark commented on app/src/Profile/dashboard-contents/General/DailyActivityDetail/index.tsx
> +        <DailyLogTime dailyLogtime={dailyLogtime} color={color} />
직접 뷰를 같이 봤으면 명쾌하게 말씀드렸을텐데 정확히 어떤 상황인지 몰라서 말씀을 못 드리겠네요 ㅜㅜ

2023-12-24 07:32 UTC, 42sungwook commented on app/src/Profile/dashboard-contents/General/DailyActivityDetail/index.tsx
>      return <DashboardContentLoading title={title} />;
뭔가 오해가 있는 것 같은데 저 버그는 "일시적"으로 보이는 상태지 계속해서 남아있는 상태가 아닌 것 같다는 말이었어요

2023-12-24 07:32 UTC, yoopark commented on app/src/Profile/dashboard-contents/General/DailyActivityDetail/index.tsx
>      return <DashboardContentLoading title={title} />;
아 로딩 단계에서 예전 게 남아있던 버그는 확인하신 거군요. 알겠습니다.

2023-12-24 07:46 UTC, merged